### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Joe118** [ericalexanderorg/SecurityBreach#56]
Hi Eric, what is the license for your SecurityBreach code? Thanks!

**Comment by ericalexanderorg** [comment]
Added the MIT license. It's a permissive license but let me know if that conflicts with your use case and we can talk about changing. My intent with this project is to help anyone make data driven decisions towards reducing risk, regardless of what tool they use (ie commercial or open source). 

https://github.com/ericalexanderorg/SecurityBreach/pull/57

**Comment by treaz** [comment]
@ericalexanderorg I don't agree with the MIT license. Since our work is voluntary, I'm not ok with others being able to "sublicense, and/or sell copies of the Software". I also wouldn't like it if any part of this project would end up in the closed-source world.
I am perfectly fine that it stays open and available for any tools, but I would prefer something like gpl.
But maybe we need to think this through better

**Comment by ericalexanderorg** [comment]
I'd like to see this data help reduce breaches and it would be a shame if the data didn't reach it's full potential due to license friction. Many businesses have policies in place that prevent the use of GPLv3 or similar licenses due to the "Same license" conditions. They wouldn't be close-sourcing per say but it could prevent them from using the data in tooling they build.

**Comment by treaz** [comment]
I'm sorry Eric, but I don't understand the use case. I'm curious to learn about it. Could you give a concrete example of how GPL would prevent a company from using this repo?
I've been in a couple of companies myself and never was GPL a problem when building internal tooling.

**Comment by ericalexanderorg** [comment]
This statement from the ASF does a good job of explaining:
https://www.apache.org/licenses/GPL-compatibility.html

I'm in uncharted territory. What are we licensing? The repo has a React UI (MIT license), data in a JSON file, and a Github action. 

- React UI: I think it has to stay MIT
- Github action: Insignificant and probably not worth worrying about
- JSON file: This is the tricky one. How is a JSON file treated when most of these license are focused on code. Is JSON code, data, or both? All moot if it's OK to scrape data from websites? https://betanews.com/2019/09/10/linkedin-data-scraping-permited/

All in all some confusing situations and I'm not sure the GPL license would do us any good, it may prevent adoption, and that could impact the size of our crowd in crowd sourced.

**Comment by treaz** [comment]
ok, let's leave it here for the moment
